picture plugin
OlegWock/anori pull request #176
Opened 2024-04-03 19:45 UTC by slayernominee

addressing https://github.com/OlegWock/anori/issues/52

<img width="1499" alt="Bildschirmfoto 2024-04-03 um 21 22 51" src="https://github.com/OlegWock/anori/assets/64646271/b1c1d0b6-78fc-489a-a9fe-68f57e5f860e">

the preview image (deer) is locally added. 

the image can be set via an url setting 
<img width="786" alt="Bildschirmfoto 2024-04-03 um 21 44 05" src="https://github.com/OlegWock/anori/assets/64646271/3227f29f-ba90-4251-b5d2-7263153044a2">

2024-04-03 19:47 UTC, slayernominee commented
the deer is btw from unsplash

2024-04-05 08:41 UTC, OlegWock requested changes
Hello! Thanks for the PR, I added couple of comments

2024-04-05 08:41 UTC, OlegWock commented on src/plugins/picture/picture-plugin.tsx
> +        <img className="Image" src={config.url !== '' ? config.url : deerExampleImage} />
I don't think we need this deer image at all. I think you can just set src like this `src={config.url}`

2024-04-05 08:41 UTC, OlegWock commented on src/plugins/picture/picture-plugin.tsx
> +    appearance: {
Could you add `withoutPadding: true` to the `appearance`? This way there won't be paddings around picture and that will look better imo

2024-04-06 05:24 UTC, slayernominee commented
i see one problem with not using a placeholder image: 
with no internet connection the mock will not have an image to show / shows the alt text
respectively with a slow internet connection it shows nothing at first 

possible solutions for this would be if we either use a placeholder image (or maybe even some random selected one from a multiple intern images) or some css animation ig

2024-04-06 09:48 UTC, OlegWock commented
That's true, but I think it will be a rare occurrence. Anori is browser extension, so user probably will have internet connection while using it anyway.  And even if they don't, picture widgets in folder won't work without internet anyway, so I don't think we need 'special treatment' for mock (which user will see a lot less often)

2024-04-07 05:51 UTC, slayernominee commented
removed it

2024-04-07 08:38 UTC, OlegWock commented
Thanks :)

2024-04-07 08:38 UTC, merged